// assets/js/components/Right/Message.vue
<template>
    <div v-if="!message?.mine" class="message-item media mb-3">
        <img :src="avatar" alt="user" width="50" class="avatar">
        <div class="media-body ml-3">
            <div class="bg-light rounded py-2 px-3 mb-2">
                <p class="text-small mb-0 text-muted">{{ message?.content }}</p>
            </div>
            <p class="small text-muted">{{ time }}</p>
        </div>
    </div>
    <div v-else class="message-item media ml-auto mb-3">
        <div class="media-body">
            <div class="bg-primary rounded py-2 px-3 mb-2">
                <p class="text-small mb-0 text-white">{{  message?.content }}</p>
            </div>
            <p class="small text-muted">{{ time }}</p>
        </div>
        <img :src="avatar" alt="user" width="50" class="avatar ml-3">
    </div>
</template>
<script>
    export default {
        props: {
            message: Object
        },
        computed: {
            time() {
                return new Date(this.message.createdAt?.date).toLocaleString();
            },

            avatar() {
                return `build/images/${this.message.userAvatar}`;
            }
        }
    }
</script>

// assets_react/js/components/Right/Message.jsx
import React from "react";

const Message = ({message}) => {
    const time = () => {
        return message.createdAt != null
        ? new Date(message.createdAt?.date).toLocaleString()
        : ''
    };

    function avatar() {
        return `build/images/${message.userAvatar}`;
    }

    return (
        <div>
            {!message?.mine ? (
            <div className="message-item media mb-3">
                <img src={avatar()} alt="user" width="50" className="avatar"/>
                <div className="media-body ml-3">
                    <div className="bg-light rounded py-2 px-3 mb-2">
                        <p className="text-small mb-0 text-muted">{message?.content}</p>
                    </div>
                    <p className="small text-muted">{time()}</p>
                </div>
            </div>
            ) : (
            <div className="message-item media ml-auto mb-3">
                <div className="media-body">
                    <div className="bg-primary rounded py-2 px-3 mb-2">
                        <p className="text-small mb-0 text-white">{message?.content}</p>
                    </div>
                    <p className="small text-muted">{time()}</p>
                </div>
                <img src={avatar()} alt="user" width="50" className="avatar ml-3"/>
            </div>
            )}
        </div>
    );
}

export default Message;
