// assets/js/components/Right/Right.vue
<template>
    <div class="col-7 px-0">
      <div class="px-4 py-5 chat-box bg-white" ref="chatBox">
        <template v-for="(message, index, key) in messages">
          <Message :message="message"/>
        </template> 
      </div>
      <Input />
    </div>
</template>

<script>
    import Message from './Message.vue';
    import Input from './Input.vue';

    export default {
        components: { Message, Input },
        computed: {
            messages() {
                return this.$store.getters.MESSAGES;
            }
        },
        methods: {
            scrollDown() {
                let chatBox = this.$refs.chatBox;
                chatBox.scrollTo(0, chatBox.scrollHeight);
            }
        },  
        mounted() {
            this.$store.dispatch('GET_MESSAGES', this.$route.params.id);
        },
        watch: {
            messages: {
                handler() {
                    this.$nextTick(() => {
                        this.scrollDown();
                    })
                },
                deep: true
            }
        }
    }
</script>

// assets_react/js/components/Right/Right.jsx
import React, { useEffect } from "react";
import Message from "./Message";
import Input from "./Input";
import { useParams } from "react-router";
import { fetchMessages } from "../../actions/conversation";
import { useDispatch, useSelector } from "react-redux";

export const Right = () => {
    const { id: conversationId} = useParams();
    const dispatch = useDispatch();
    const messages = useSelector((state) => state.conversation.messages);

    useEffect(() => {
        fetchMessages(dispatch, conversationId);
    }, [conversationId]);

    return (
        <div className="col-7 px-0">
            <div className="px-4 py-5 chat-box bg-white" refxxx="chatBox">
            { messages.map((item, index) => {
                return <Message message={item} key={index}/>
            })}
            </div>
            <Input />
        </div>
    );
}

export default Right;
